[package]
name = "elembic"
version = "0.0.1"
compiler = "0.11.0"
repository = "https://github.com/PgBiel/elembic"
entrypoint = "src/lib.typ"
authors = ["PgBiel <https://github.com/PgBiel>"]
categories = ["scripting", "utility"]
license = "MIT OR Apache-2.0"
description = "Custom elements and types in pure Typst"
keywords = ["element", "type", "validation", "styling"]

[tool.typst-test]
tests = "test/unit"
