[book]
authors = ["PgBiel"]
language = "en"
multilingual = false
src = "src"
title = "The Elemmic Handbook"

[output.html]
git-repository-url = "https://github.com/PgBiel/elemmic"
edit-url-template = "https://github.com/PgBiel/elemmic/edit/main/docs/book/{path}"
