[book]
authors = ["PgBiel"]
language = "en"
multilingual = false
src = "src"
title = "The Elembic Handbook"

[output.html]
git-repository-url = "https://github.com/PgBiel/elembic"
edit-url-template = "https://github.com/PgBiel/elembic/edit/main/docs/book/{path}"

[preprocessor.replace-pkg-version]
command = "./bin/replace-pkg-version.sh"
