#import "/test/unit/base.typ": empty
#show: empty

#import "/src/lib.typ" as e: field

#let wock = e.element.declare(
  "wock",
  display: it => {},
  fields: (
    field("color", color, default: blue),
    field("inner", content, default: [])
  ),
  prefix: ""
)

#show: e.set_(wock, color: red)
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.set_(wock, color: red)
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.set_(wock, color: red)
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.set_(wock, color: red)
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.set_(wock, color: red)
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.set_(wock, color: red)
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.set_(wock, color: red)
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.set_(wock, color: red)
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.set_(wock, color: red)
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.set_(wock, color: red)
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.set_(wock, color: red) // 10
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.set_(wock, color: red)
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.set_(wock, color: red)
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.set_(wock, color: red)
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.set_(wock, color: red)
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.set_(wock, color: red)
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.set_(wock, color: red)
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.set_(wock, color: red)
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.set_(wock, color: red)
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.set_(wock, color: red)
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.set_(wock, color: red) // 20
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.set_(wock, color: red)
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.set_(wock, color: red)
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.set_(wock, color: red)
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.set_(wock, color: red)
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.set_(wock, color: red)
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.set_(wock, color: red)
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.set_(wock, color: red)
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.set_(wock, color: red)
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.set_(wock, color: red)
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.set_(wock, color: red) // 30
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.set_(wock, color: red)
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.set_(wock, color: red)
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.set_(wock, color: red)
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.set_(wock, color: red)
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.set_(wock, color: red)
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.set_(wock, color: red)
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.set_(wock, color: red)
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.set_(wock, color: red)
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.set_(wock, color: red)
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.set_(wock, color: red) // 40
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.set_(wock, color: red)
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.set_(wock, color: red)
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.set_(wock, color: red)
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.set_(wock, color: red)
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.set_(wock, color: red)
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.set_(wock, color: red)
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.set_(wock, color: red)
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.set_(wock, color: red)
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.set_(wock, color: red)
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.set_(wock, color: red) // 50
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.set_(wock, color: red)
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.set_(wock, color: red)
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.set_(wock, color: red)
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.set_(wock, color: red)
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.set_(wock, color: red)
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.set_(wock, color: red)
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.set_(wock, color: red)
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.set_(wock, color: red)
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.set_(wock, color: red)
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.set_(wock, color: red) // 60
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.set_(wock, color: red)
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.set_(wock, color: red)
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.set_(wock, color: red)
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.set_(wock, color: red)
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.set_(wock, color: red)
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.set_(wock, color: red)
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.set_(wock, color: red)
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.set_(wock, color: red)
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.set_(wock, color: red)
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.set_(wock, color: red) // 70
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.set_(wock, color: red)
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.set_(wock, color: red)
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.set_(wock, color: red)
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.set_(wock, color: red)
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.set_(wock, color: red)
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.set_(wock, color: red)
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.set_(wock, color: red)
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.apply(
  e.set_(wock, color: red),
  e.set_(wock, inner: [Road]),
)
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.set_(wock, color: red)
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.set_(wock, color: red) // 80
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.set_(wock, color: red)
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.set_(wock, color: red)
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.set_(wock, color: red)
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.set_(wock, color: red)
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.set_(wock, color: red)
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.set_(wock, color: red)
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.set_(wock, color: red)
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.set_(wock, color: red)
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.set_(wock, color: red)
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.set_(wock, color: red) // 90
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.set_(wock, color: red)
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.set_(wock, color: red)
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.set_(wock, color: red)
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.set_(wock, color: red)
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.set_(wock, color: red)
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.set_(wock, color: red)
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.set_(wock, color: red)
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))
#show: e.set_(wock, color: red)
#set outline(title: [Roadster])
#set bibliography(title: [Mount])
#show: e.set_(wock, color: yellow) // 100
#set table(fill: red)
#set box(stroke: black)
#set list(marker: ("a", "b"))

#wock()
#e.get(get => assert.eq(get(wock).color, yellow))
#e.get(get => assert.eq(get(wock).inner, [Road]))

#context {
  assert.eq(outline.title, [Roadster])
  assert.eq(bibliography.title, [Mount])
  assert.eq(table.fill, red)
  assert.eq(box.stroke, stroke(black))
  assert.eq(list.marker, ([a], [b]))
}
