#import "../src/lib.typ" as e: element, field, types

#let (wock, wock-e) = element(
  "wock",
  it => {
    [#it.body]
  },
  fields: (
    field("body", content, default: ""),
    field("color", color, default: red),
    field("something", int, default: 10),
  )
)

#let (dock, dock-e) = element(
  "dock",
  it => {
    [#it.body]
  },
  fields: (
    field("body", content, default: ""),
  )
)

#show: e.set_(wock-e, body: "a")
#show: e.set_(wock-e, body: "b")
#show: e.set_(wock-e, body: "c")
#show: e.set_(wock-e, body: "a")
#show: e.set_(dock-e, body: "b")

#show: e.apply(
  e.set_(wock-e, body: "a"),
  e.set_(wock-e, body: "b"),
  e.set_(wock-e, body: "c"),
  e.set_(wock-e, body: "a"),
  e.set_(dock-e, body: "b")
)

#show: e.set_(wock-e, body: "c")
#show: e.set_(wock-e, body: "a")
#show: e.set_(wock-e, body: "b")
#show: e.set_(wock-e, body: "c")
#show: e.set_(wock-e, body: "a")
#show: e.set_(wock-e, body: "b")
#show: e.set_(wock-e, body: "c")
#show: e.set_(dock-e, body: "a")
#show: e.set_(dock-e, body: "b")
#show: e.set_(dock-e, body: "c")
#show: e.set_(dock-e, body: "a")
#show: e.set_(dock-e, body: "b")
#show: e.set_(dock-e, body: "c")
#show: e.apply(
  e.set_(wock-e, something: 400),
  e.set_(wock-e, something: 500),
)
#show: e.set_(dock-e, body: "a")
#show: e.set_(dock-e, body: "b")
#show: e.set_(dock-e, body: "c")
#show: e.set_(dock-e, body: "a")
#show: e.set_(wock-e, body: "b")
#show: e.set_(wock-e, body: "c")
#show: e.set_(wock-e, body: "a")
#show: e.set_(wock-e, body: "b")
#show: e.set_(wock-e, body: "c")

#show: e.apply(
  e.set_(wock-e, body: "a"),
  e.set_(wock-e, body: "b"),
  e.set_(wock-e, body: "c"),
  e.set_(wock-e, body: "a"),
  e.set_(dock-e, body: "b")
)

#show: e.set_(wock-e, body: "a")

#show: e.apply(
  e.set_(wock-e, color: yellow),
  e.set_(wock-e, color: blue),
)

#show: e.set_(wock-e, body: "b")
#show: e.set_(wock-e, body: "a")
#show: e.set_(wock-e, body: "b")
#show: e.set_(wock-e, body: "c")
#show: e.set_(wock-e, body: "a")
#show: e.set_(dock-e, body: "b")
#show: e.set_(wock-e, body: "c")
#show: e.set_(wock-e, body: "a")
#show: e.set_(wock-e, body: "b")
#show: e.set_(wock-e, body: "c")
#show: e.set_(wock-e, body: "a")
#show: e.set_(wock-e, body: "b")
#show: e.set_(wock-e, body: "c")
#show: e.set_(dock-e, body: "a")
#show: e.set_(dock-e, body: "b")
#show: e.set_(dock-e, body: "c")
#show: e.set_(dock-e, body: "a")
#show: e.set_(dock-e, body: "b")
#show: e.set_(dock-e, body: "c")
#show: e.set_(dock-e, body: "a")
#show: e.set_(dock-e, body: "b")
#show: e.set_(dock-e, body: "c")
#show: e.set_(dock-e, body: "a")
#show: e.set_(wock-e, body: "b")
#show: e.set_(wock-e, body: "c")
#show: e.set_(wock-e, body: "a")
#show: e.set_(wock-e, body: "b")
#show: e.set_(wock-e, body: "c")
#show: e.set_(wock-e, body: "a")
#show: e.set_(wock-e, body: "b")
#show: e.set_(wock-e, body: "a")
#show: e.set_(wock-e, body: "b")
#show: e.set_(wock-e, body: "c")
#show: e.set_(wock-e, body: "a")
#show: e.set_(dock-e, body: "b")
#show: e.set_(wock-e, body: "c")
#show: e.set_(wock-e, body: "a")
#show: e.set_(wock-e, body: "b")
#show: e.set_(wock-e, body: "c")
#show: e.set_(wock-e, body: "a")
#show: e.set_(wock-e, body: "b")
#show: e.set_(wock-e, body: "c")
#show: e.set_(dock-e, body: "a")
#show: e.set_(dock-e, body: "b")
#show: e.set_(dock-e, body: "c")
#show: e.set_(dock-e, body: "a")
#show: e.set_(dock-e, body: "b")
#show: e.set_(dock-e, body: "c")
#show: e.set_(dock-e, body: "a")
#show: e.set_(dock-e, body: "b")
#show: e.set_(dock-e, body: "c")
#show: e.set_(dock-e, body: "a")
#show: e.set_(wock-e, body: "b")
#show: e.set_(wock-e, body: "c")
#show: e.set_(wock-e, body: "a")
#show: e.set_(wock-e, body: "b")
#show: e.set_(wock-e, body: "c")
#show: e.set_(wock-e, body: "a")
#show: e.set_(wock-e, body: "b")
#show: e.set_(wock-e, body: "a")
#show: e.set_(wock-e, body: "b")
#show: e.set_(wock-e, body: "c")
#show: e.set_(wock-e, body: "a")
#show: e.set_(dock-e, body: "b")
#show: e.set_(wock-e, body: "c")
#show: e.set_(wock-e, body: "a")
#show: e.set_(wock-e, body: "b")
#show: e.set_(wock-e, body: "c")
#show: e.set_(wock-e, body: "a")
#show: e.set_(wock-e, body: "b")
#show: e.set_(wock-e, body: "c")
#show: e.set_(dock-e, body: "a")
#show: e.set_(dock-e, body: "b")
#show: e.set_(dock-e, body: "c")
#show: e.set_(dock-e, body: "a")
#show: e.set_(dock-e, body: "b")
#show: e.set_(dock-e, body: "c")
#show: e.set_(dock-e, body: "a")
#show: e.set_(dock-e, body: "b")
#show: e.set_(dock-e, body: "c")
#show: e.set_(dock-e, body: "a")
#show: e.set_(wock-e, body: "b")
#show: e.set_(wock-e, body: "c")
#show: e.set_(wock-e, body: "a")
#show: e.set_(wock-e, body: "b")
#show: e.set_(wock-e, body: "c")
#show: e.set_(wock-e, body: "a")
#show: e.set_(wock-e, body: "b")
#show: e.set_(wock-e, body: "a")
#show: e.set_(wock-e, body: "b")
#show: e.set_(wock-e, body: "c")
#show: e.set_(wock-e, body: "a")
#show: e.set_(dock-e, body: "b")
#show: e.set_(wock-e, body: "c")
#show: e.set_(wock-e, body: "a")
#show: e.set_(wock-e, body: "b")
#show: e.set_(wock-e, body: "c")
#show: e.set_(wock-e, body: "a")
#show: e.set_(wock-e, body: "b")
#show: e.set_(wock-e, body: "c")
#show: e.set_(dock-e, body: "a")
#show: e.set_(dock-e, body: "b")
#show: e.set_(dock-e, body: "c")
#show: e.set_(dock-e, body: "a")
#show: e.set_(dock-e, body: "b")
#show: e.set_(dock-e, body: "c")
#show: e.set_(dock-e, body: "a")
#show: e.set_(dock-e, body: "b")
#show: e.set_(dock-e, body: "c")
#show: e.set_(dock-e, body: "a")
#show: e.set_(wock-e, body: "b")
#show: e.set_(wock-e, body: "c")
#show: e.set_(wock-e, body: "a")
#show: e.set_(wock-e, body: "b")
#show: e.set_(wock-e, body: "c")
#show: e.set_(wock-e, body: "a")
#show: e.set_(wock-e, body: "b")
#show: e.set_(wock-e, body: "a")
#show: e.set_(wock-e, body: "b")
#show: e.set_(wock-e, body: "c")
#show: e.set_(wock-e, body: "a")
#show: e.set_(dock-e, body: "b")
#show: e.set_(wock-e, body: "c")
#show: e.set_(wock-e, body: "a")
#show: e.set_(wock-e, body: "b")
#show: e.set_(wock-e, body: "c")
#show: e.set_(wock-e, body: "a")
#show: e.set_(wock-e, body: "b")
#show: e.set_(wock-e, body: "c")
#show: e.set_(dock-e, body: "a")
#show: e.set_(dock-e, body: "b")
#show: e.set_(dock-e, body: "c")
#show: e.set_(dock-e, body: "a")
#show: e.set_(dock-e, body: "b")
#show: e.set_(dock-e, body: "c")
#show: e.set_(dock-e, body: "a")
#show: e.set_(dock-e, body: "b")
#show: e.set_(dock-e, body: "c")
#show: e.set_(dock-e, body: "a")
#show: e.set_(wock-e, body: "b")
#show: e.set_(wock-e, body: "c")
#show: e.set_(wock-e, body: "a")
#show: e.set_(wock-e, body: "b")
#show: e.set_(wock-e, body: "c")
#show: e.set_(wock-e, body: "a")
#show: e.set_(wock-e, body: "b")
#show: e.set_(wock-e, body: "a")
#show: e.set_(wock-e, body: "b")
#show: e.set_(wock-e, body: "c")
#show: e.set_(wock-e, body: "a")
#show: e.set_(dock-e, body: "b")
#show: e.set_(wock-e, body: "c")
#show: e.set_(wock-e, body: "a")
#show: e.set_(wock-e, body: "b")
#show: e.set_(wock-e, body: "c")
#show: e.set_(wock-e, body: "a")
#show: e.set_(wock-e, body: "b")
#show: e.set_(wock-e, body: "c")
#show: e.set_(dock-e, body: "a")
#show: e.set_(dock-e, body: "b")
#show: e.set_(dock-e, body: "c")
#show: e.set_(dock-e, body: "a")
#show: e.set_(dock-e, body: "b")
#show: e.set_(dock-e, body: "c")
#show: e.set_(dock-e, body: "a")
#show: e.set_(dock-e, body: "b")
#show: e.set_(dock-e, body: "c")
#show: e.set_(dock-e, body: "a")
#show: e.set_(wock-e, body: "b")
#show: e.set_(wock-e, body: "c")
#show: e.set_(wock-e, body: "a")
#show: e.set_(wock-e, body: "b")
#show: e.set_(wock-e, body: "c")
#show: e.set_(wock-e, body: "a")
#show: e.set_(wock-e, body: "b")

#wock()

// Ensure the set rules in 'apply' worked
#(wock-e.get)(v => { assert.eq(v.color, blue); assert.eq(v.something, 500) })
