#import "/src/lib.typ" as e: field, types

#let wock = e.element.declare(
  "wock",
  display: it => {
    [#it.body]
  },
  fields: (
    field("body", content, default: ""),
    field("color", color, default: red),
    field("something", int, default: 10),
  ),
  prefix: ""
)

#let dock = e.element.declare(
  "dock",
  display: it => {
    [#it.body]
  },
  fields: (
    field("body", content, default: ""),
  ),
  prefix: ""
)

#show: e.set_(wock, body: "a")
#show: e.set_(wock, body: "b")
#show: e.set_(wock, body: "c")
#show: e.set_(wock, body: "a")
#show: e.set_(dock, body: "b")

#show: e.apply(
  e.set_(wock, body: "a"),
  e.set_(wock, body: "b"),
  e.set_(wock, body: "c"),
  e.set_(wock, body: "a"),
  e.set_(dock, body: "b")
)

#show: e.set_(wock, body: "c")
#show: e.set_(wock, body: "a")
#show: e.set_(wock, body: "b")
#show: e.set_(wock, body: "c")
#show: e.set_(wock, body: "a")
#show: e.set_(wock, body: "b")
#show: e.set_(wock, body: "c")
#show: e.set_(dock, body: "a")
#show: e.set_(dock, body: "b")
#show: e.set_(dock, body: "c")
#show: e.set_(dock, body: "a")
#show: e.set_(dock, body: "b")
#show: e.set_(dock, body: "c")
#show: e.apply(
  e.set_(wock, something: 400),
  e.set_(wock, something: 500),
)
#show: e.set_(dock, body: "a")
#show: e.set_(dock, body: "b")
#show: e.set_(dock, body: "c")
#show: e.set_(dock, body: "a")
#show: e.set_(wock, body: "b")
#show: e.set_(wock, body: "c")
#show: e.set_(wock, body: "a")
#show: e.set_(wock, body: "b")
#show: e.set_(wock, body: "c")

#show: e.apply(
  e.set_(wock, body: "a"),
  e.set_(wock, body: "b"),
  e.set_(wock, body: "c"),
  e.set_(wock, body: "a"),
  e.set_(dock, body: "b")
)

#show: e.set_(wock, body: "a")

#show: e.apply(
  e.set_(wock, color: yellow),
  e.set_(wock, color: blue),
)

#show: e.set_(wock, body: "b")
#show: e.set_(wock, body: "a")
#show: e.set_(wock, body: "b")
#show: e.set_(wock, body: "c")
#show: e.set_(wock, body: "a")
#show: e.set_(dock, body: "b")
#show: e.set_(wock, body: "c")
#show: e.set_(wock, body: "a")
#show: e.set_(wock, body: "b")
#show: e.set_(wock, body: "c")
#show: e.set_(wock, body: "a")
#show: e.set_(wock, body: "b")
#show: e.set_(wock, body: "c")
#show: e.set_(dock, body: "a")
#show: e.set_(dock, body: "b")
#show: e.set_(dock, body: "c")
#show: e.set_(dock, body: "a")
#show: e.set_(dock, body: "b")
#show: e.set_(dock, body: "c")
#show: e.set_(dock, body: "a")
#show: e.set_(dock, body: "b")
#show: e.set_(dock, body: "c")
#show: e.set_(dock, body: "a")
#show: e.set_(wock, body: "b")
#show: e.set_(wock, body: "c")
#show: e.set_(wock, body: "a")
#show: e.set_(wock, body: "b")
#show: e.set_(wock, body: "c")
#show: e.set_(wock, body: "a")
#show: e.set_(wock, body: "b")
#show: e.set_(wock, body: "a")
#show: e.set_(wock, body: "b")
#show: e.set_(wock, body: "c")
#show: e.set_(wock, body: "a")
#show: e.set_(dock, body: "b")
#show: e.set_(wock, body: "c")
#show: e.set_(wock, body: "a")
#show: e.set_(wock, body: "b")
#show: e.set_(wock, body: "c")
#show: e.set_(wock, body: "a")
#show: e.set_(wock, body: "b")
#show: e.set_(wock, body: "c")
#show: e.set_(dock, body: "a")
#show: e.set_(dock, body: "b")
#show: e.set_(dock, body: "c")
#show: e.set_(dock, body: "a")
#show: e.set_(dock, body: "b")
#show: e.set_(dock, body: "c")
#show: e.set_(dock, body: "a")
#show: e.set_(dock, body: "b")
#show: e.set_(dock, body: "c")
#show: e.set_(dock, body: "a")
#show: e.set_(wock, body: "b")
#show: e.set_(wock, body: "c")
#show: e.set_(wock, body: "a")
#show: e.set_(wock, body: "b")
#show: e.set_(wock, body: "c")
#show: e.set_(wock, body: "a")
#show: e.set_(wock, body: "b")
#show: e.set_(wock, body: "a")
#show: e.set_(wock, body: "b")
#show: e.set_(wock, body: "c")
#show: e.set_(wock, body: "a")
#show: e.set_(dock, body: "b")
#show: e.set_(wock, body: "c")
#show: e.set_(wock, body: "a")
#show: e.set_(wock, body: "b")
#show: e.set_(wock, body: "c")
#show: e.set_(wock, body: "a")
#show: e.set_(wock, body: "b")
#show: e.set_(wock, body: "c")
#show: e.set_(dock, body: "a")
#show: e.set_(dock, body: "b")
#show: e.set_(dock, body: "c")
#show: e.set_(dock, body: "a")
#show: e.set_(dock, body: "b")
#show: e.set_(dock, body: "c")
#show: e.set_(dock, body: "a")
#show: e.set_(dock, body: "b")
#show: e.set_(dock, body: "c")
#show: e.set_(dock, body: "a")
#show: e.set_(wock, body: "b")
#show: e.set_(wock, body: "c")
#show: e.set_(wock, body: "a")
#show: e.set_(wock, body: "b")
#show: e.set_(wock, body: "c")
#show: e.set_(wock, body: "a")
#show: e.set_(wock, body: "b")
#show: e.set_(wock, body: "a")
#show: e.set_(wock, body: "b")
#show: e.set_(wock, body: "c")
#show: e.set_(wock, body: "a")
#show: e.set_(dock, body: "b")
#show: e.set_(wock, body: "c")
#show: e.set_(wock, body: "a")
#show: e.set_(wock, body: "b")
#show: e.set_(wock, body: "c")
#show: e.set_(wock, body: "a")
#show: e.set_(wock, body: "b")
#show: e.set_(wock, body: "c")
#show: e.set_(dock, body: "a")
#show: e.set_(dock, body: "b")
#show: e.set_(dock, body: "c")
#show: e.set_(dock, body: "a")
#show: e.set_(dock, body: "b")
#show: e.set_(dock, body: "c")
#show: e.set_(dock, body: "a")
#show: e.set_(dock, body: "b")
#show: e.set_(dock, body: "c")
#show: e.set_(dock, body: "a")
#show: e.set_(wock, body: "b")
#show: e.set_(wock, body: "c")
#show: e.set_(wock, body: "a")
#show: e.set_(wock, body: "b")
#show: e.set_(wock, body: "c")
#show: e.set_(wock, body: "a")
#show: e.set_(wock, body: "b")
#show: e.set_(wock, body: "a")
#show: e.set_(wock, body: "b")
#show: e.set_(wock, body: "c")
#show: e.set_(wock, body: "a")
#show: e.set_(dock, body: "b")
#show: e.set_(wock, body: "c")
#show: e.set_(wock, body: "a")
#show: e.set_(wock, body: "b")
#show: e.set_(wock, body: "c")
#show: e.set_(wock, body: "a")
#show: e.set_(wock, body: "b")
#show: e.set_(wock, body: "c")
#show: e.set_(dock, body: "a")
#show: e.set_(dock, body: "b")
#show: e.set_(dock, body: "c")
#show: e.set_(dock, body: "a")
#show: e.set_(dock, body: "b")
#show: e.set_(dock, body: "c")
#show: e.set_(dock, body: "a")
#show: e.set_(dock, body: "b")
#show: e.set_(dock, body: "c")
#show: e.set_(dock, body: "a")
#show: e.set_(wock, body: "b")
#show: e.set_(wock, body: "c")
#show: e.set_(wock, body: "a")
#show: e.set_(wock, body: "b")
#show: e.set_(wock, body: "c")
#show: e.set_(wock, body: "a")
#show: e.set_(wock, body: "b")
#show: e.set_(wock, body: "a")
#show: e.set_(wock, body: "b")
#show: e.set_(wock, body: "c")
#show: e.set_(wock, body: "a")
#show: e.set_(dock, body: "b")
#show: e.set_(wock, body: "c")
#show: e.set_(wock, body: "a")
#show: e.set_(wock, body: "b")
#show: e.set_(wock, body: "c")
#show: e.set_(wock, body: "a")
#show: e.set_(wock, body: "b")
#show: e.set_(wock, body: "c")
#show: e.set_(dock, body: "a")
#show: e.set_(dock, body: "b")
#show: e.set_(dock, body: "c")
#show: e.set_(dock, body: "a")
#show: e.set_(dock, body: "b")
#show: e.set_(dock, body: "c")
#show: e.set_(dock, body: "a")
#show: e.set_(dock, body: "b")
#show: e.set_(dock, body: "c")
#show: e.set_(dock, body: "a")
#show: e.set_(wock, body: "b")
#show: e.set_(wock, body: "c")
#show: e.set_(wock, body: "a")
#show: e.set_(wock, body: "b")
#show: e.set_(wock, body: "c")
#show: e.set_(wock, body: "a")
#show: e.set_(wock, body: "b")

#wock()

// Ensure the set rules in 'apply' worked
#e.get(get => { assert.eq(get(wock).color, blue); assert.eq(get(wock).something, 500) })
